version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
      - ./www/config:/var/www/config
      - ./www/lib/Controller:/var/www/lib/Controller
      - ./www/lib/Model:/var/www/lib/Model
    depends_on:
      - php
    container_name: web

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
      - ./www/config:/var/www/config
      - ./www/lib/Controller:/var/www/lib/Controller
      - ./www/lib/Model:/var/www/lib/Model
    tty: true
    stdin_open: true
    depends_on:
      - db
    container_name: php

  db:
    build: ./db
    # restart: always
    hostname: my_mysql
    # ports:
    #   - 13306:3306
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./ec_shop_database.sql:/docker-entrypoint-initdb.d/ec_shop_database.sql    
    environment:
      - .env
    container_name: db_mysql

