FROM php:7.2-fpm

RUN docker-php-ext-install pdo_mysql

COPY php.ini /usr/local/etc/php/
# COPY ./www/html /var/www/html
# COPY ./www/config /var/www/config
# COPY ./www/lib/Controller /var/www/lib/Controller
# COPY ./www/lib/Model /var/www/lib/Model
